name: Auto Assign Issues

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: OWASP BLT-Action Auto-assign Issue and unassign after 5 days
        uses: OWASP-BLT/BLT-Action@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'https://github.com/OWASP-BLT/BLT-Action'